# Generated by Django 4.1.2 on 2022-10-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report", options={"ordering": ("-created",)},
        ),
    ]
